DROP_TABLES_SQL = [
    "IF OBJECT_ID('FACT_ORDER_ITEMS', 'U') IS NOT NULL DROP TABLE FACT_ORDER_ITEMS;",
    "IF OBJECT_ID('DIM_REVIEWS', 'U') IS NOT NULL DROP TABLE DIM_REVIEWS;",
    "IF OBJECT_ID('DIM_ORDERS', 'U') IS NOT NULL DROP TABLE dbo.DIM_ORDERS;",
    "IF OBJECT_ID('DIM_CITIES', 'U') IS NOT NULL DROP TABLE DIM_CITIES;",
    "IF OBJECT_ID('DIM_PRODUCTS', 'U') IS NOT NULL DROP TABLE DIM_PRODUCTS;",
    "IF OBJECT_ID('DIM_TIMESTAMP', 'U') IS NOT NULL DROP TABLE dbo.DIM_TIMESTAMP;",
]
